"use strict";
exports.__esModule = true;
var movie_1 = require("./movie");
var Professional_1 = require("./Professional");
var peli1 = new movie_1.Movie("Capitán América: El primer vengador", 2011, "estadounidense", "acción");
var peli2 = new movie_1.Movie("Malditos Bastardos", 2009, "estadounidense", "bélica");
var peli3 = new movie_1.Movie("Mar adentro", 2004, "espanyola", "drama");
var peli4 = new movie_1.Movie("La maldición", 2003, "japonesa", "terror");
var pro1 = new Professional_1.Professional("Brad Pitt", 57, "masculino", 75, 1.8, "rubio", "azules", "caucásico", false, "norteamericano", 2, "actor");
var pro2 = new Professional_1.Professional("Scarlett Johansson", 36, "femenino", 54, 1.6, "rubio", "marrones", "caucásico", true, "norteamericano", 0, "actor");
var pro3 = new Professional_1.Professional("Robert Downey Jr.", 56, "masculino", 57, 1.74, "castaño", "marrones", "caucásico", true, "norteamericano", 0, "actor");
var pro4 = new Professional_1.Professional("Chris Hemsworth", 38, "masculino", 72, 1.9, "castaño", "marrones", "caucásico", true, "australiano", 0, "actor");
var pro5 = new Professional_1.Professional("Stan Lee", 98, "masculino", 66, 1.8, "blanco", "marrones", "caucásico", true, "norteamericano", 0, "writer");
var pro6 = new Professional_1.Professional("Kevin Feige", 48, "masculino", 71, 1.82, "castaño", "marrones", "caucásico", true, "norteamericano", 0, "producer");
peli1.actors = [pro1, pro2, pro3, pro4];
peli1.writer = pro5;
peli1.producer = pro6;
peli1.printMovie();
peli2.printMovie();
peli3.printMovie();
peli4.printMovie();
