"use strict";
exports.__esModule = true;
exports.pro6 = exports.pro5 = exports.pro4 = exports.pro3 = exports.pro2 = exports.pro1 = void 0;
var Professional_1 = require("./Professional");
var pro1;
exports.pro1 = pro1;
var pro2;
exports.pro2 = pro2;
var pro3;
exports.pro3 = pro3;
var pro4;
exports.pro4 = pro4;
var pro5;
exports.pro5 = pro5;
var pro6;
exports.pro6 = pro6;
exports.pro1 = pro1 = new Professional_1.Professional("Brad Pitt", 57, "masculino", 75, 1.8, "rubio", "azules", "caucásico", false, "norteamericano", 2, "actor");
exports.pro2 = pro2 = new Professional_1.Professional("Scarlett Johansson", 36, "femenino", 54, 1.6, "rubio", "marrones", "caucásico", true, "norteamericano", 0, "actor");
exports.pro3 = pro3 = new Professional_1.Professional("Robert Downey Jr.", 56, "masculino", 57, 1.74, "castaño", "marrones", "caucásico", true, "norteamericano", 0, "actor");
exports.pro4 = pro4 = new Professional_1.Professional("Chris Hemsworth", 38, "masculino", 72, 1.9, "castaño", "marrones", "caucásico", true, "australiano", 0, "actor");
exports.pro5 = pro5 = new Professional_1.Professional("Stan Lee", 98, "masculino", 66, 1.8, "blanco", "marrones", "caucásico", true, "norteamericano", 0, "writer");
exports.pro6 = pro6 = new Professional_1.Professional("Kevin Feige", 48, "masculino", 71, 1.82, "castaño", "marrones", "caucásico", true, "norteamericano", 0, "producer");
pro1.printProfessional();
pro2.printProfessional();
pro3.printProfessional();
pro4.printProfessional();
pro5.printProfessional();
pro6.printProfessional();
